
# # Packages
# FIND_PACKAGE(OpenGL REQUIRED)
# INCLUDE_DIRECTORIES(${OPENGL_INCLUDE_DIRS})
# LINK_DIRECTORIES(${OPENGL_LIBRARY_DIRS})
# ADD_DEFINITIONS(${OPENGL_DEFINITIONS})

# MESSAGE(STATUS "OpenGL: ${OPENGL_LIBRARIES}")
# LIST(APPEND stdgl_libraries ${OPENGL_gl_LIBRARY})